#!/usr/bin/env python3
"""compile-schemas.py — compiler for research-step's assets/schemas.yaml.

Three stages:
  parse  — load schemas.yaml and parse the type mini-DSL and the flow trees.
  check  — resolve every cross-reference: type fields -> types/vocabulary/builtins,
           task outputs -> types, flow steps -> tasks, {workflow: X} chain
           items -> workflows, and every `input:` entry -> an upstream node in the
           flow's expanded graph (or in some flow that embeds it). Also diffs
           scripts/task-output-keys.sh against the compiler's own answer.
  emit   — assets/compiled/<task>.schema.json (one self-contained JSON Schema
           per task), assets/compiled/<flow>.mmd (one fully-expanded mermaid
           diagram per flow), and assets/compiled/loops.json (every flow as a
           machine-readable graph — nodes, edges, chain commands, missions —
           with the task schemas embedded, for downstream renderers).

Contract notes encoded here (they mirror the comments in schemas.yaml):
  - top-level output_json is closed (additionalProperties: false) — every output
    is a declared, typed key;
  - nested objects are open (additionalProperties: true) — agent payloads nest
    verbatim, extra nested fields are always permitted;
  - a `?` suffix marks a field or an output key optional (e.g. `mcts_provenance?:`,
    or a step's `"run?": run` when the run deep-link is only sometimes produced);
    unmarked names are required. In a YAML inline mapping the key must be quoted
    (`"run?": run`) because a bare `?` is not legal there.

Exit: 0 ok (warnings allowed) · 1 errors (all printed).
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

SCHEMA_VERSION = 2
# Shape of assets/compiled/loops.json. Bump when the JSON structure changes;
# downstream renderers gate on it before drawing anything.
LOOPS_FORMAT_VERSION = 1
BUILTINS = {
    "string": {"type": "string"},
    "number": {"type": "number"},
    "boolean": {"type": "boolean"},
    "object": {"type": "object"},
}
# ref(<type>): a string field holding a repo-root-relative path to a record kept
# off beads metadata. The compiled property carries an x-path-ref annotation that
# validate-output.sh reads to deep-validate the file against <type>; the type is
# a normal reference, so it travels in $defs and stays reachable on its own.
REF_RE = re.compile(r"^ref\((\w+)\)$")
PATH_REF_KEYWORD = "x-path-ref"
JSON_DIALECT = "https://json-schema.org/draft/2020-12/schema"
GENERATED_NOTE = (
    "generated by scripts/compile-schemas.py from assets/schemas.yaml; do not edit"
)


def field_name(raw):
    """Split a DSL field name into (name, optional)."""
    if raw.endswith("?"):
        return raw[:-1], True
    return raw, False


class Node:
    """One node of a flow tree (step, group, or sub-flow embedding)."""

    def __init__(self, name, kind, parent, origin):
        self.name = name
        self.kind = kind  # step | group | embed
        self.parent = parent
        self.origin = origin  # (flow_name, path-within-that-flow tuple)
        self.mission = ""
        self.inputs = []
        self.cli_cmds = []
        self.workflow = None  # embed only: the flow it expands
        self.replan = False
        self.children = []
        self.preorder = -1

    def ancestors(self):
        n = self.parent
        while n is not None:
            yield n
            n = n.parent

    def subtree(self):
        yield self
        for c in self.children:
            yield from c.subtree()

    def path(self):
        parts = []
        n = self
        while n.parent is not None:
            parts.append(n.name)
            n = n.parent
        return tuple(reversed(parts))


class Compiler:
    def __init__(self, doc):
        self.doc = doc
        self.errors = []
        self.warnings = []
        self.vocabulary = {}
        self.outputs = {}
        self.steps = {}
        self.loops_raw = {}

    def err(self, ctx, msg):
        self.errors.append(f"{ctx}: {msg}")

    def warn(self, ctx, msg):
        self.warnings.append(f"{ctx}: {msg}")

    # ---------- parse + check: sections ----------

    def check_document(self):
        d = self.doc
        if not isinstance(d, dict):
            self.err("document", "schemas.yaml is not a mapping")
            return
        for key in ("version", "config", "vocabulary", "workflows", "outputs"):
            if key not in d:
                self.err("document", f"missing top-level section '{key}'")
        if d.get("version") != SCHEMA_VERSION:
            self.err("version", f"expected {SCHEMA_VERSION}, got {d.get('version')!r}")
        for k in d:
            if k not in ("version", "config", "vocabulary", "workflows", "outputs"):
                self.err("document", f"unknown top-level section '{k}'")

        config = d.get("config") or {}
        if not isinstance(config, dict):
            self.err("config", "must be a mapping of key: scalar-default")
        else:
            for k, v in config.items():
                if not isinstance(v, (int, float, str, bool)):
                    self.err(
                        f"config.{k}",
                        f"default must be a scalar, got {type(v).__name__}",
                    )

        vocabulary = d.get("vocabulary") or {}
        if not isinstance(vocabulary, dict):
            self.err("vocabulary", "must be a mapping of name: [values]")
            vocabulary = {}
        for name, values in vocabulary.items():
            ctx = f"vocabulary.{name}"
            if not isinstance(values, list) or not values:
                self.err(ctx, "must be a non-empty list")
                continue
            if any(not isinstance(v, str) for v in values):
                self.err(ctx, "values must all be strings")
                continue
            if len(set(values)) != len(values):
                self.err(ctx, "values must be unique")
            self.vocabulary[name] = values

        outputs = d.get("outputs") or {}
        if not isinstance(outputs, dict):
            self.err("outputs", "must be a mapping of name: definition")
            outputs = {}
        self.outputs = dict(outputs)

        # name collisions across the namespaces a reference can hit
        for name in self.outputs:
            if name in BUILTINS:
                self.err(f"outputs.{name}", "collides with a builtin scalar name")
            if name in self.vocabulary:
                self.err(f"outputs.{name}", "collides with a vocabulary name")
        for name in self.vocabulary:
            if name in BUILTINS:
                self.err(f"vocabulary.{name}", "collides with a builtin scalar name")

        for name, definition in self.outputs.items():
            self.check_expr(definition, f"outputs.{name}")

        # Steps (each step's output contract) are collected while parsing loops,
        # since a step is defined inline where it runs. See parse_loop.
        loops = d.get("workflows") or {}
        if not isinstance(loops, dict):
            self.err("workflows", "must be a mapping of workflow_name: definition")
            loops = {}
        self.loops_raw = loops

    # ---------- the type expression DSL ----------

    def check_expr(self, expr, ctx):
        if isinstance(expr, str):
            name, opt = field_name(expr)
            if opt:
                self.err(
                    ctx,
                    "the '?' optional marker belongs on field names, not type names",
                )
            m = REF_RE.match(name)
            if m:
                if m.group(1) not in self.outputs:
                    self.err(ctx, f"ref() target '{m.group(1)}' is not a declared type")
            elif (
                name not in BUILTINS
                and name not in self.vocabulary
                and name not in self.outputs
            ):
                self.err(ctx, f"unknown type or enum '{name}'")
        elif isinstance(expr, list):
            if len(expr) != 1:
                self.err(
                    ctx,
                    f"array type must have exactly one element type, got {len(expr)}",
                )
            else:
                self.check_expr(expr[0], f"{ctx}[]")
        elif isinstance(expr, dict):
            if not expr:
                self.err(ctx, "inline object must declare at least one field")
            for raw, sub in expr.items():
                name, _ = field_name(raw)
                self.check_expr(sub, f"{ctx}.{name}")
        else:
            self.err(ctx, f"unsupported type expression: {expr!r}")

    def type_refs(self, expr):
        """Yield the named types an expression references (no emission)."""
        if isinstance(expr, str):
            m = REF_RE.match(expr)
            if m:
                yield m.group(1)
            elif expr in self.outputs:
                yield expr
        elif isinstance(expr, list):
            for item in expr:
                yield from self.type_refs(item)
        elif isinstance(expr, dict):
            for sub in expr.values():
                yield from self.type_refs(sub)

    def compile_expr(self, expr):
        if isinstance(expr, str):
            m = REF_RE.match(expr)
            if m:
                return {"type": "string", PATH_REF_KEYWORD: m.group(1)}
            if expr in BUILTINS:
                return dict(BUILTINS[expr])
            if expr in self.vocabulary:
                return {"enum": list(self.vocabulary[expr])}
            if expr in self.outputs:
                return {"$ref": f"#/$defs/{expr}"}
            return {}  # already reported by check_expr
        if isinstance(expr, list) and len(expr) == 1:
            return {"type": "array", "items": self.compile_expr(expr[0])}
        if isinstance(expr, dict):
            return self.compile_object(expr)
        return {}

    def compile_object(self, fields):
        props, required = {}, []
        for raw, sub in fields.items():
            name, optional = field_name(raw)
            props[name] = self.compile_expr(sub)
            if not optional:
                required.append(name)
        # nested objects stay open: agent payloads nest verbatim, extra
        # nested fields are always permitted (see the note in schemas.yaml)
        return {
            "type": "object",
            "properties": props,
            "required": required,
            "additionalProperties": True,
        }

    def type_closure(self, seed):
        seen = set()
        frontier = set(seed)
        while frontier:
            name = frontier.pop()
            if name in seen or name not in self.outputs:
                continue
            seen.add(name)
            frontier |= set(self.type_refs(self.outputs[name])) - seen
        return seen

    def compile_step_schema(self, task):
        output = self.steps[task]
        props, required = {}, []
        for key, expr in output.items():
            name, optional = field_name(key)
            props[name] = self.compile_expr(expr)
            if not optional:
                required.append(name)
        deps = {t for expr in output.values() for t in self.type_refs(expr)}
        defs = {
            name: self.compile_expr(self.outputs[name])
            for name in sorted(self.type_closure(deps))
        }
        schema = {
            "$schema": JSON_DIALECT,
            "$id": f"asta-research-step/{task}.schema.json",
            "$comment": GENERATED_NOTE,
            "title": task,
            "type": "object",
            "properties": props,
            "required": required,
            # top level is closed: every output is a declared, typed key
            "additionalProperties": False,
        }
        if defs:
            schema["$defs"] = defs
        return schema

    # ---------- loops: parse ----------
    # A loop has a mission and an ordered `children` list; each child is either a
    # step (carries `output`, optional `cli`/`input`), an inline sub-loop (carries
    # `children`), or a bare-name string referencing another defined loop (reuse).

    LOOP_KEYS = {"mission", "replan", "children"}
    STEP_KEYS = {"mission", "input", "cli", "output"}

    def parse_loop(self, loop_name):
        raw = self.loops_raw[loop_name]
        ctx = f"loops.{loop_name}"
        root = Node(loop_name, "group", None, (loop_name, ()))
        if not isinstance(raw, dict):
            self.err(ctx, "loop must be a mapping")
            return root
        self.fill_loop(root, raw, loop_name, ctx)
        return root

    def fill_loop(self, node, raw, loop_name, ctx):
        node.mission = raw.get("mission", "")
        if not isinstance(node.mission, str) or not node.mission:
            self.err(ctx, "loop must carry a mission")
            if not isinstance(node.mission, str):
                node.mission = ""
        node.replan = raw.get("replan", False)
        if not isinstance(node.replan, bool):
            self.err(ctx, "replan must be a boolean")
            node.replan = False
        for k in raw:
            if k not in self.LOOP_KEYS:
                self.err(ctx, f"unknown loop key '{k}' (loops carry mission, replan, children)")
        children = raw.get("children", [])
        if not isinstance(children, list) or not children:
            self.err(ctx, "loop must have a non-empty children list")
            children = []
        for i, item in enumerate(children):
            child = self.parse_child(item, node, loop_name, f"{ctx}.children[{i}]")
            if child is not None:
                node.children.append(child)

    def parse_child(self, item, parent, loop_name, ctx):
        if isinstance(item, str):  # bare name -> reference to a defined loop
            if item not in self.loops_raw:
                self.err(ctx, f"reference to unknown loop '{item}'")
                return None
            node = Node(item, "embed", parent, (loop_name, parent.origin[1] + (item,)))
            node.workflow = item
            return node
        if not isinstance(item, dict) or len(item) != 1:
            self.err(ctx, "a child is a loop name (string) or a one-key mapping {name: {...}}")
            return None
        name, body = next(iter(item.items()))
        nctx = f"loops.{loop_name}.{name}"
        if not isinstance(body, dict):
            self.err(nctx, "child body must be a mapping")
            return None
        origin = (loop_name, parent.origin[1] + (name,))
        if "children" in body:  # inline sub-loop
            node = Node(name, "group", parent, origin)
            self.fill_loop(node, body, loop_name, nctx)
            return node
        return self.parse_step(name, body, parent, loop_name, origin, nctx)

    def parse_step(self, name, body, parent, loop_name, origin, ctx):
        node = Node(name, "step", parent, origin)
        node.mission = body.get("mission", "")
        if not isinstance(node.mission, str) or not node.mission:
            self.err(ctx, "step must carry a mission")
        for k in body:
            if k not in self.STEP_KEYS:
                self.err(ctx, f"unknown step key '{k}' (steps carry mission, input, cli, output)")
        inputs = body.get("input", [])
        if not isinstance(inputs, list) or any(not isinstance(i, str) for i in inputs):
            self.err(ctx, "input must be a list of step names")
            inputs = []
        node.inputs = list(inputs)
        cli = body.get("cli", [])
        if not isinstance(cli, list):
            self.err(ctx, "cli must be a list of asta subcommands (omit for a reasoning-only step)")
            cli = []
        for c in cli:
            if not isinstance(c, str) or not c.startswith("asta "):
                self.err(ctx, f"cli item must be an 'asta <subcommand>' string: {c!r}")
            else:
                node.cli_cmds.append(c)
        output = body.get("output")
        if not isinstance(output, dict) or not output:
            self.err(ctx, "step must declare a non-empty output mapping")
            return node
        for key, expr in output.items():
            self.check_expr(expr, f"{ctx}.output.{key}")
        prev = self.steps.get(name)
        if prev is not None and prev != output:
            self.err(ctx, f"step '{name}' reused with a different output contract; reused steps must match")
        self.steps[name] = output
        return node

    # ---------- loops: expansion + input resolution ----------

    def expand_flow(self, flow_name, parsed, stack=()):
        """Build a fresh expanded tree for flow_name; embeds become groups
        wrapping the embedded flow's (recursively expanded) children."""
        if flow_name in stack:
            self.err(
                f"loops.{flow_name}",
                f"workflow embedding cycle: {' -> '.join(stack + (flow_name,))}",
            )
            return None

        def clone(node, parent):
            copy = Node(node.name, node.kind, parent, node.origin)
            copy.mission, copy.inputs = node.mission, list(node.inputs)
            copy.cli_cmds, copy.replan = list(node.cli_cmds), node.replan
            copy.workflow = node.workflow
            if node.kind == "embed" and node.workflow:
                inner = self.expand_flow(node.workflow, parsed, stack + (flow_name,))
                if inner is not None:
                    # the embed group speaks for the sub-workflow it expands
                    copy.mission = inner.mission
                    copy.replan = inner.replan
                    for c in inner.children:
                        c.parent = copy
                        copy.children.append(c)
            else:
                for c in node.children:
                    copy.children.append(clone(c, copy))
            return copy

        root = clone(parsed[flow_name], None)
        for i, n in enumerate(root.subtree()):
            n.preorder = i
        return root

    @staticmethod
    def resolve_input(step, name):
        """Nearest-ancestor-scope, upstream-only resolution: walk outward from
        the step; in each scope pick the closest preceding node with that name."""
        ancestors = set(step.ancestors())
        for scope in step.ancestors():
            candidates = [
                n
                for n in scope.subtree()
                if n.name == name and n.preorder < step.preorder and n not in ancestors
            ]
            if candidates:
                return max(candidates, key=lambda n: n.preorder)
        return None

    def check_flows(self):
        parsed = {name: self.parse_loop(name) for name in self.loops_raw}
        if self.errors:
            # expansion and resolution on a broken parse just compounds noise
            return {}
        expanded = {name: self.expand_flow(name, parsed) for name in self.loops_raw}
        if any(v is None for v in expanded.values()) or self.errors:
            return {}

        # (origin_flow, origin_path, input) -> {context_flow: resolved?}
        results = {}
        for context, root in expanded.items():
            for node in root.subtree():
                for inp in node.inputs:
                    key = (node.origin[0], node.origin[1], inp)
                    results.setdefault(key, {})[context] = (
                        self.resolve_input(node, inp) is not None
                    )

        for (flow, path, inp), by_context in sorted(results.items()):
            if not any(by_context.values()):
                ctx = f"workflows.{flow}.{'.'.join(path)}"
                contexts = ", ".join(sorted(by_context))
                self.err(
                    ctx,
                    f"input '{inp}' does not resolve to any upstream node "
                    f"in any context (checked: {contexts})",
                )
        return expanded

    # ---------- script compatibility ----------

    def check_scripts(self, skill_dir):
        script = Path(skill_dir) / "scripts" / "task-output-keys.sh"
        if not script.is_file():
            self.err("scripts", f"{script} not found")
            return

        def query(task):
            return subprocess.run(
                ["bash", str(script), task], capture_output=True, text=True
            )

        # each call is bash -> python3 -> full YAML parse; run them concurrently
        with ThreadPoolExecutor(max_workers=8) as pool:
            futures = {task: pool.submit(query, task) for task in sorted(self.steps)}
            bogus = pool.submit(query, "definitely_not_a_task")

        for task, future in futures.items():
            r = future.result()
            if r.returncode != 0:
                self.err(
                    f"scripts.task-output-keys.{task}",
                    f"exited {r.returncode}: {r.stderr.strip()}",
                )
                continue
            got = r.stdout.split()
            want = [field_name(k)[0] for k in self.steps[task]]
            if got != want:
                self.err(
                    f"scripts.task-output-keys.{task}",
                    f"key drift: script says [{' '.join(got)}], schema says [{' '.join(want)}]",
                )
        if bogus.result().returncode != 3:
            self.err(
                "scripts.task-output-keys",
                f"unknown task_type should exit 3, got {bogus.result().returncode}",
            )

    # ---------- mermaid emission ----------

    @staticmethod
    def node_id(node):
        return re.sub(r"[^A-Za-z0-9_]", "_", "__".join(node.path())) or "root"

    @staticmethod
    def label(text):
        return text.replace('"', "#quot;")

    def emit_mermaid(self, flow_name, root):
        lines = [
            f"%% {flow_name} — {GENERATED_NOTE}",
            "%% thick ==> : a loop's child order  ·  thin --> : data input  ·  dashed: input from outside this loop",
            "flowchart TD",
            "  classDef external stroke-dasharray: 3 3,color:#888888",
        ]
        edges, externals, loop_styles, order_edges = [], {}, [], []

        # Every non-step node is a loop and renders as a subgraph (recursively),
        # so nested loops always read as loops. A per-subgraph `style` sets the
        # uniform loop fill (mermaid ignores classDef fill on nested subgraphs);
        # fan-out loops (replan) get a dashed border.
        def walk(node, depth):
            pad = "  " * depth
            nid = self.node_id(node)
            if node.kind == "step":
                lines.append(f'{pad}{nid}["{self.label(node.name)}"]')
                return
            title = node.name + (" — fan-out (one branch per item)" if node.replan else "")
            lines.append(f'{pad}subgraph {nid}["{self.label(title)}"]')
            for c in node.children:
                walk(c, depth + 1)
            lines.append(f"{pad}end")
            # outer loops (those that contain sub-loops) get no fill so the nested
            # loops read clearly; leaf loops (children are all steps) are filled.
            has_subloop = any(c.kind != "step" for c in node.children)
            fill = "fill:none,stroke:#6699cc" if has_subloop else "fill:#eef6ff,stroke:#6699cc"
            if node.replan:
                fill += ",stroke-dasharray: 6 4"
            loop_styles.append(f"  style {nid} {fill}")

        for child in root.children:
            walk(child, 1)

        # data-input edges (and inputs satisfied outside this loop, dashed)
        input_pairs = set()
        for node in root.subtree():
            for inp in node.inputs:
                src = self.resolve_input(node, inp)
                if src is not None:
                    input_pairs.add((self.node_id(src), self.node_id(node)))
                    edges.append(f"  {self.node_id(src)} --> {self.node_id(node)}")
                else:
                    ext = externals.setdefault(
                        inp, f"ext__{re.sub(r'[^A-Za-z0-9_]', '_', inp)}"
                    )
                    edges.append(f"  {ext} -.-> {self.node_id(node)}")

        # child-order edges: connect each loop's children in array order (left to
        # right), so the hierarchy is explicit even for loops with no data input
        # (e.g. summarize, reflection). Skip a pair that a data edge already draws.
        def order(node):
            kids = node.children
            for a, b in zip(kids, kids[1:]):
                pair = (self.node_id(a), self.node_id(b))
                if pair not in input_pairs:
                    order_edges.append(f"  {pair[0]} ==> {pair[1]}")
            for k in kids:
                order(k)
        order(root)

        for inp, ext in sorted(externals.items()):
            lines.append(f'  {ext}(["{self.label(inp)} (external)"]):::external')
        lines.extend(order_edges)
        lines.extend(edges)
        lines.extend(loop_styles)
        return "\n".join(lines) + "\n"

    # ---------- loops.json emission ----------

    def emit_flow_graph(self, root):
        """One flow as a graph: the same expanded tree and input resolution the
        mermaid emitter walks, as data. Nodes come in preorder so a node's
        `parent` always appears earlier (the React Flow sub-flow contract)."""
        nodes = []
        for node in root.subtree():
            if node is root:
                continue
            entry = {
                "id": self.node_id(node),
                "parent": None if node.parent is root else self.node_id(node.parent),
                "kind": node.kind,
                "name": node.name,
                "mission": node.mission,
                "replan": node.replan,
            }
            if node.kind == "step":
                entry["task"] = node.name
                entry["cli"] = list(node.cli_cmds)
                entry["inputs"] = list(node.inputs)
            elif node.kind == "embed":
                entry["workflow"] = node.workflow
            nodes.append(entry)

        edges, externals = [], {}
        for node in root.subtree():
            for inp in node.inputs:
                src = self.resolve_input(node, inp)
                if src is not None:
                    source = self.node_id(src)
                    external = False
                else:
                    source = externals.setdefault(
                        inp, f"ext__{re.sub(r'[^A-Za-z0-9_]', '_', inp)}"
                    )
                    external = True
                edges.append({
                    "source": source,
                    "target": self.node_id(node),
                    "input": inp,
                    "external": external,
                })
        # inputs satisfied outside this flow: synthetic nodes, like the
        # mermaid emitter's dashed "(external)" stadiums
        for inp, ext in sorted(externals.items()):
            entry = {
                "id": ext,
                "parent": None,
                "kind": "external",
                "name": inp,
                "mission": "",
                "replan": False,
            }
            if inp in self.steps:
                entry["task"] = inp
            nodes.append(entry)
        return {"mission": root.mission, "nodes": nodes, "edges": edges}

    def emit_workworkflows_doc(self, expanded, schemas):
        """The whole loops.json document. Task schemas are embedded once,
        keyed by task name (nodes reference them via their `task` field), so
        a renderer needs no further fetches; `output` is the raw mini-DSL
        expression for compact key/type display."""
        return {
            "format_version": LOOPS_FORMAT_VERSION,
            "schema_version": SCHEMA_VERSION,
            "$comment": GENERATED_NOTE,
            "tasks": {
                task: {"output": self.steps[task], "schema": schemas[task]}
                for task in sorted(self.steps)
            },
            "workflows": {
                name: self.emit_flow_graph(root) for name, root in expanded.items()
            },
        }

    # ---------- driver ----------

    def run(self, skill_dir=None, script_check=True):
        self.check_document()
        expanded = self.check_flows()

        # unreachable-type warning: everything should hang off some task
        if self.steps:
            seeds = {
                t
                for output in self.steps.values()
                for expr in output.values()
                for t in self.type_refs(expr)
            }
            reachable = self.type_closure(seeds)
            for name in self.outputs:
                if name not in reachable:
                    self.warn(f"types.{name}", "not reachable from any task output")

        if script_check and skill_dir is not None and not self.errors:
            self.check_scripts(skill_dir)

        schemas = {}
        diagrams = {}
        workflows_doc = {}
        if not self.errors:
            schemas = {task: self.compile_step_schema(task) for task in self.steps}
            diagrams = {
                name: self.emit_mermaid(name, root) for name, root in expanded.items()
            }
            workflows_doc = self.emit_workworkflows_doc(expanded, schemas)
        return schemas, diagrams, workflows_doc


def main(argv=None):
    repo = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--skill-dir",
        type=Path,
        default=repo / "skills" / "research-step",
        help="the research-step skill directory (default: skills/research-step)",
    )
    ap.add_argument(
        "--no-script-check",
        action="store_true",
        help="skip the task-output-keys.sh compatibility check",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="validate only; do not write assets/compiled/",
    )
    args = ap.parse_args(argv)

    try:
        import yaml
    except ImportError:
        print(
            "compile-schemas: python3 cannot import yaml (PyYAML) — pip install pyyaml",
            file=sys.stderr,
        )
        return 1

    schemas_path = args.skill_dir / "assets" / "schemas.yaml"
    try:
        with open(schemas_path) as f:
            doc = yaml.safe_load(f)
    except Exception as e:
        print(f"compile-schemas: cannot read {schemas_path}: {e}", file=sys.stderr)
        return 1

    compiler = Compiler(doc)
    schemas, diagrams, workflows_doc = compiler.run(
        skill_dir=args.skill_dir, script_check=not args.no_script_check
    )

    for w in compiler.warnings:
        print(f"compile-schemas: warning: {w}", file=sys.stderr)
    if compiler.errors:
        for e in compiler.errors:
            print(f"compile-schemas: error: {e}", file=sys.stderr)
        print(f"compile-schemas: {len(compiler.errors)} error(s)", file=sys.stderr)
        return 1

    if not args.check:
        out_dir = args.skill_dir / "assets" / "compiled"
        out_dir.mkdir(parents=True, exist_ok=True)
        for stale in (
            list(out_dir.glob("*.schema.json"))
            + list(out_dir.glob("*.mmd"))
            + list(out_dir.glob("loops.json"))
        ):
            stale.unlink()
        for task, schema in schemas.items():
            (out_dir / f"{task}.schema.json").write_text(
                json.dumps(schema, indent=2, sort_keys=True) + "\n"
            )
        for flow, mmd in diagrams.items():
            (out_dir / f"{flow}.mmd").write_text(mmd)
        (out_dir / "loops.json").write_text(
            json.dumps(workflows_doc, indent=2, sort_keys=True) + "\n"
        )

    print(
        f"compile-schemas: ok — {len(compiler.outputs)} outputs, "
        f"{len(schemas)} task schemas, {len(diagrams)} flow diagrams, loops.json"
        + ("" if args.check else f" -> {args.skill_dir / 'assets' / 'compiled'}")
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
