#!/usr/bin/env python3
"""compile-schemas.py — compiler for research-step's assets/schemas.yaml.

Three stages:
  parse  — load schemas.yaml and parse the type mini-DSL and the flow trees.
  check  — resolve every cross-reference: type fields -> types/enums/builtins,
           task outputs -> types, flow steps -> tasks, {workflow: X} chain
           items -> flows, and every `input:` entry -> an upstream node in the
           flow's expanded graph (or in some flow that embeds it). Also diffs
           scripts/task-output-keys.sh against the compiler's own answer.
  emit   — assets/compiled/<task>.schema.json (one self-contained JSON Schema
           per task), assets/compiled/<flow>.mmd (one fully-expanded mermaid
           diagram per flow), and assets/compiled/flows.json (every flow as a
           machine-readable graph — nodes, edges, chain commands, missions —
           with the task schemas embedded, for downstream renderers).

Contract notes encoded here (they mirror the comments in schemas.yaml):
  - top-level output_json is closed (additionalProperties: false) — byproducts
    go in artifacts;
  - nested objects are open (additionalProperties: true) — agent payloads nest
    verbatim, extra nested fields are always permitted;
  - a `?` suffix on a field name marks it optional (e.g. `mcts_provenance?:`);
    unmarked fields are required.

Exit: 0 ok (warnings allowed) · 1 errors (all printed).
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

SCHEMA_VERSION = 2
# Shape of assets/compiled/flows.json. Bump when the JSON structure changes;
# downstream renderers gate on it before drawing anything.
FLOWS_FORMAT_VERSION = 1
BUILTINS = {
    "string": {"type": "string"},
    "number": {"type": "number"},
    "boolean": {"type": "boolean"},
    "object": {"type": "object"},
}
RESERVED_NODE_KEYS = {"mission", "input", "chain", "replan"}
JSON_DIALECT = "https://json-schema.org/draft/2020-12/schema"
GENERATED_NOTE = (
    "generated by scripts/compile-schemas.py from assets/schemas.yaml; do not edit"
)


def field_name(raw):
    """Split a DSL field name into (name, optional)."""
    if raw.endswith("?"):
        return raw[:-1], True
    return raw, False


class Node:
    """One node of a flow tree (step, group, or sub-flow embedding)."""

    def __init__(self, name, kind, parent, origin):
        self.name = name
        self.kind = kind  # step | group | embed
        self.parent = parent
        self.origin = origin  # (flow_name, path-within-that-flow tuple)
        self.mission = ""
        self.inputs = []
        self.chain_cmds = []
        self.workflow = None  # embed only: the flow it expands
        self.replan = False
        self.children = []
        self.preorder = -1

    def ancestors(self):
        n = self.parent
        while n is not None:
            yield n
            n = n.parent

    def subtree(self):
        yield self
        for c in self.children:
            yield from c.subtree()

    def path(self):
        parts = []
        n = self
        while n.parent is not None:
            parts.append(n.name)
            n = n.parent
        return tuple(reversed(parts))


class Compiler:
    def __init__(self, doc):
        self.doc = doc
        self.errors = []
        self.warnings = []
        self.enums = {}
        self.types = {}
        self.tasks = {}
        self.flows_raw = {}

    def err(self, ctx, msg):
        self.errors.append(f"{ctx}: {msg}")

    def warn(self, ctx, msg):
        self.warnings.append(f"{ctx}: {msg}")

    # ---------- parse + check: sections ----------

    def check_document(self):
        d = self.doc
        if not isinstance(d, dict):
            self.err("document", "schemas.yaml is not a mapping")
            return
        for key in ("version", "config", "enums", "types", "tasks", "flows"):
            if key not in d:
                self.err("document", f"missing top-level section '{key}'")
        if d.get("version") != SCHEMA_VERSION:
            self.err("version", f"expected {SCHEMA_VERSION}, got {d.get('version')!r}")
        for k in d:
            if k not in ("version", "config", "enums", "types", "tasks", "flows"):
                self.err("document", f"unknown top-level section '{k}'")

        config = d.get("config") or {}
        if not isinstance(config, dict):
            self.err("config", "must be a mapping of key: scalar-default")
        else:
            for k, v in config.items():
                if not isinstance(v, (int, float, str, bool)):
                    self.err(
                        f"config.{k}",
                        f"default must be a scalar, got {type(v).__name__}",
                    )

        enums = d.get("enums") or {}
        if not isinstance(enums, dict):
            self.err("enums", "must be a mapping of name: [values]")
            enums = {}
        for name, values in enums.items():
            ctx = f"enums.{name}"
            if not isinstance(values, list) or not values:
                self.err(ctx, "must be a non-empty list")
                continue
            if any(not isinstance(v, str) for v in values):
                self.err(ctx, "values must all be strings")
                continue
            if len(set(values)) != len(values):
                self.err(ctx, "values must be unique")
            self.enums[name] = values

        types = d.get("types") or {}
        if not isinstance(types, dict):
            self.err("types", "must be a mapping of name: definition")
            types = {}
        self.types = dict(types)

        # name collisions across the three namespaces a reference can hit
        for name in self.types:
            if name in BUILTINS:
                self.err(f"types.{name}", "collides with a builtin scalar name")
            if name in self.enums:
                self.err(f"types.{name}", "collides with an enum name")
        for name in self.enums:
            if name in BUILTINS:
                self.err(f"enums.{name}", "collides with a builtin scalar name")

        for name, definition in self.types.items():
            self.check_expr(definition, f"types.{name}")

        tasks = d.get("tasks") or {}
        if not isinstance(tasks, dict):
            self.err("tasks", "must be a mapping of task_type: {output: ...}")
            tasks = {}
        for name, spec in tasks.items():
            ctx = f"tasks.{name}"
            if not isinstance(spec, dict) or set(spec) != {"output"}:
                self.err(ctx, "must be exactly {output: {...}}")
                continue
            output = spec["output"]
            if not isinstance(output, dict) or not output:
                self.err(ctx, "output must be a non-empty mapping")
                continue
            for key, expr in output.items():
                if key.endswith("?"):
                    self.err(
                        f"{ctx}.output", f"top-level key '{key}' may not be optional"
                    )
                self.check_expr(expr, f"{ctx}.output.{key}")
            if output.get("artifacts") != ["artifact"]:
                self.err(ctx, "output must include artifacts: [artifact]")
            self.tasks[name] = output

        flows = d.get("flows") or {}
        if not isinstance(flows, dict):
            self.err("flows", "must be a mapping of flow_name: tree")
            flows = {}
        self.flows_raw = flows

    # ---------- the type expression DSL ----------

    def check_expr(self, expr, ctx):
        if isinstance(expr, str):
            name, opt = field_name(expr)
            if opt:
                self.err(
                    ctx,
                    "the '?' optional marker belongs on field names, not type names",
                )
            if (
                name not in BUILTINS
                and name not in self.enums
                and name not in self.types
            ):
                self.err(ctx, f"unknown type or enum '{name}'")
        elif isinstance(expr, list):
            if len(expr) != 1:
                self.err(
                    ctx,
                    f"array type must have exactly one element type, got {len(expr)}",
                )
            else:
                self.check_expr(expr[0], f"{ctx}[]")
        elif isinstance(expr, dict):
            if not expr:
                self.err(ctx, "inline object must declare at least one field")
            for raw, sub in expr.items():
                name, _ = field_name(raw)
                self.check_expr(sub, f"{ctx}.{name}")
        else:
            self.err(ctx, f"unsupported type expression: {expr!r}")

    def type_refs(self, expr):
        """Yield the named types an expression references (no emission)."""
        if isinstance(expr, str):
            if expr in self.types:
                yield expr
        elif isinstance(expr, list):
            for item in expr:
                yield from self.type_refs(item)
        elif isinstance(expr, dict):
            for sub in expr.values():
                yield from self.type_refs(sub)

    def compile_expr(self, expr):
        if isinstance(expr, str):
            if expr in BUILTINS:
                return dict(BUILTINS[expr])
            if expr in self.enums:
                return {"enum": list(self.enums[expr])}
            if expr in self.types:
                return {"$ref": f"#/$defs/{expr}"}
            return {}  # already reported by check_expr
        if isinstance(expr, list) and len(expr) == 1:
            return {"type": "array", "items": self.compile_expr(expr[0])}
        if isinstance(expr, dict):
            return self.compile_object(expr)
        return {}

    def compile_object(self, fields):
        props, required = {}, []
        for raw, sub in fields.items():
            name, optional = field_name(raw)
            props[name] = self.compile_expr(sub)
            if not optional:
                required.append(name)
        # nested objects stay open: agent payloads nest verbatim, extra
        # nested fields are always permitted (see the note in schemas.yaml)
        return {
            "type": "object",
            "properties": props,
            "required": required,
            "additionalProperties": True,
        }

    def type_closure(self, seed):
        seen = set()
        frontier = set(seed)
        while frontier:
            name = frontier.pop()
            if name in seen or name not in self.types:
                continue
            seen.add(name)
            frontier |= set(self.type_refs(self.types[name])) - seen
        return seen

    def compile_task_schema(self, task):
        output = self.tasks[task]
        props, required = {}, []
        for key, expr in output.items():
            name, _ = field_name(key)
            props[name] = self.compile_expr(expr)
            required.append(name)
        deps = {t for expr in output.values() for t in self.type_refs(expr)}
        defs = {
            name: self.compile_expr(self.types[name])
            for name in sorted(self.type_closure(deps))
        }
        schema = {
            "$schema": JSON_DIALECT,
            "$id": f"asta-research-step/{task}.schema.json",
            "$comment": GENERATED_NOTE,
            "title": task,
            "type": "object",
            "properties": props,
            "required": required,
            # top level is closed: byproducts go in artifacts
            "additionalProperties": False,
        }
        if defs:
            schema["$defs"] = defs
        return schema

    # ---------- flows: parse ----------

    def parse_flow(self, flow_name):
        raw = self.flows_raw[flow_name]
        ctx = f"flows.{flow_name}"
        root = Node(flow_name, "group", None, (flow_name, ()))
        if not isinstance(raw, dict):
            self.err(ctx, "flow must be a mapping")
            return root
        root.mission = raw.get("mission", "")
        if not isinstance(root.mission, str) or not root.mission:
            self.err(ctx, "flow must carry a mission")
        for key, value in raw.items():
            if key == "mission":
                continue
            if key in RESERVED_NODE_KEYS:
                self.err(ctx, f"flow root may not carry '{key}'")
                continue
            child = self.parse_node(key, value, root, flow_name, f"{ctx}.{key}")
            if child is not None:
                root.children.append(child)
        if not root.children:
            self.err(ctx, "flow has no steps")
        return root

    def parse_node(self, name, raw, parent, flow_name, ctx):
        if not isinstance(raw, dict):
            self.err(ctx, "node must be a mapping")
            return None
        origin = (flow_name, parent.origin[1] + (name,))
        mission = raw.get("mission", "")
        if not isinstance(mission, str) or not mission:
            self.err(ctx, "node must carry a mission")

        child_keys = [k for k in raw if k not in RESERVED_NODE_KEYS]
        bad_children = [k for k in child_keys if not isinstance(raw[k], dict)]
        for k in bad_children:
            self.err(f"{ctx}.{k}", "unknown node attribute (children must be mappings)")
        child_keys = [k for k in child_keys if k not in bad_children]

        inputs = raw.get("input", None)
        if inputs is not None and (
            not isinstance(inputs, list) or any(not isinstance(i, str) for i in inputs)
        ):
            self.err(ctx, "input must be a list of node names")
            inputs = []

        replan = raw.get("replan", False)
        if not isinstance(replan, bool):
            self.err(ctx, "replan must be a boolean")
            replan = False
        if replan and "chain" in raw:
            self.err(ctx, "replan is only valid on groups (branches created at replan)")

        if "chain" not in raw:  # group
            node = Node(name, "group", parent, origin)
            node.mission = mission
            node.replan = replan
            if inputs is not None:
                self.err(ctx, "groups may not carry input — inputs live on steps")
            if not child_keys:
                self.err(ctx, "group has no children (a step needs a chain, even [])")
            for k in child_keys:
                child = self.parse_node(k, raw[k], node, flow_name, f"{ctx}.{k}")
                if child is not None:
                    node.children.append(child)
            return node

        chain = raw["chain"]
        if not isinstance(chain, list):
            self.err(ctx, "chain must be a list")
            chain = []
        workflow_items = [c for c in chain if isinstance(c, dict)]

        if workflow_items:  # sub-flow embedding
            node = Node(name, "embed", parent, origin)
            node.mission = mission
            if len(chain) != 1:
                self.err(
                    ctx, "a {workflow: ...} chain item must be the chain's only item"
                )
            item = workflow_items[0]
            if set(item) != {"workflow", "mission"}:
                self.err(ctx, "workflow chain item must be exactly {workflow, mission}")
            wf = item.get("workflow")
            if wf not in self.flows_raw:
                self.err(ctx, f"unknown workflow '{wf}'")
            else:
                node.workflow = wf
            if inputs is not None:
                self.err(ctx, "embed nodes may not carry input")
            if child_keys:
                self.err(ctx, "embed nodes may not have children")
            return node

        # step
        node = Node(name, "step", parent, origin)
        node.mission = mission
        node.inputs = list(inputs or [])
        if name not in self.tasks:
            self.err(
                ctx,
                f"step name is not a declared task (known: {', '.join(sorted(self.tasks))})",
            )
        for c in chain:
            if not isinstance(c, str):
                self.err(ctx, f"chain item must be a string or {{workflow}}: {c!r}")
            elif not c.startswith("asta "):
                self.err(
                    ctx, f"chain command does not look like an asta command: '{c}'"
                )
            else:
                node.chain_cmds.append(c)
        if child_keys:
            self.err(ctx, f"steps may not have children: {', '.join(child_keys)}")
        return node

    # ---------- flows: expansion + input resolution ----------

    def expand_flow(self, flow_name, parsed, stack=()):
        """Build a fresh expanded tree for flow_name; embeds become groups
        wrapping the embedded flow's (recursively expanded) children."""
        if flow_name in stack:
            self.err(
                f"flows.{flow_name}",
                f"workflow embedding cycle: {' -> '.join(stack + (flow_name,))}",
            )
            return None

        def clone(node, parent):
            copy = Node(node.name, node.kind, parent, node.origin)
            copy.mission, copy.inputs = node.mission, list(node.inputs)
            copy.chain_cmds, copy.replan = list(node.chain_cmds), node.replan
            copy.workflow = node.workflow
            if node.kind == "embed" and node.workflow:
                inner = self.expand_flow(node.workflow, parsed, stack + (flow_name,))
                if inner is not None:
                    for c in inner.children:
                        c.parent = copy
                        copy.children.append(c)
            else:
                for c in node.children:
                    copy.children.append(clone(c, copy))
            return copy

        root = clone(parsed[flow_name], None)
        for i, n in enumerate(root.subtree()):
            n.preorder = i
        return root

    @staticmethod
    def resolve_input(step, name):
        """Nearest-ancestor-scope, upstream-only resolution: walk outward from
        the step; in each scope pick the closest preceding node with that name."""
        ancestors = set(step.ancestors())
        for scope in step.ancestors():
            candidates = [
                n
                for n in scope.subtree()
                if n.name == name and n.preorder < step.preorder and n not in ancestors
            ]
            if candidates:
                return max(candidates, key=lambda n: n.preorder)
        return None

    def check_flows(self):
        parsed = {name: self.parse_flow(name) for name in self.flows_raw}
        if self.errors:
            # expansion and resolution on a broken parse just compounds noise
            return {}
        expanded = {name: self.expand_flow(name, parsed) for name in self.flows_raw}
        if any(v is None for v in expanded.values()) or self.errors:
            return {}

        # (origin_flow, origin_path, input) -> {context_flow: resolved?}
        results = {}
        for context, root in expanded.items():
            for node in root.subtree():
                for inp in node.inputs:
                    key = (node.origin[0], node.origin[1], inp)
                    results.setdefault(key, {})[context] = (
                        self.resolve_input(node, inp) is not None
                    )

        for (flow, path, inp), by_context in sorted(results.items()):
            if not any(by_context.values()):
                ctx = f"flows.{flow}.{'.'.join(path)}"
                contexts = ", ".join(sorted(by_context))
                self.err(
                    ctx,
                    f"input '{inp}' does not resolve to any upstream node "
                    f"in any context (checked: {contexts})",
                )
        return expanded

    # ---------- script compatibility ----------

    def check_scripts(self, skill_dir):
        script = Path(skill_dir) / "scripts" / "task-output-keys.sh"
        if not script.is_file():
            self.err("scripts", f"{script} not found")
            return

        def query(task):
            return subprocess.run(
                ["bash", str(script), task], capture_output=True, text=True
            )

        # each call is bash -> python3 -> full YAML parse; run them concurrently
        with ThreadPoolExecutor(max_workers=8) as pool:
            futures = {task: pool.submit(query, task) for task in sorted(self.tasks)}
            bogus = pool.submit(query, "definitely_not_a_task")

        for task, future in futures.items():
            r = future.result()
            if r.returncode != 0:
                self.err(
                    f"scripts.task-output-keys.{task}",
                    f"exited {r.returncode}: {r.stderr.strip()}",
                )
                continue
            got = r.stdout.split()
            want = [field_name(k)[0] for k in self.tasks[task]]
            if got != want:
                self.err(
                    f"scripts.task-output-keys.{task}",
                    f"key drift: script says [{' '.join(got)}], schema says [{' '.join(want)}]",
                )
        if bogus.result().returncode != 3:
            self.err(
                "scripts.task-output-keys",
                f"unknown task_type should exit 3, got {bogus.result().returncode}",
            )

    # ---------- mermaid emission ----------

    @staticmethod
    def node_id(node):
        return re.sub(r"[^A-Za-z0-9_]", "_", "__".join(node.path())) or "root"

    @staticmethod
    def label(text):
        return text.replace('"', "#quot;")

    def emit_mermaid(self, flow_name, root):
        lines = [
            f"%% {flow_name} — {GENERATED_NOTE}",
            "%% solid arrows: input wiring · dashed: inputs satisfied outside this flow",
            "flowchart TD",
            "  classDef replan stroke-dasharray: 6 4",
            "  classDef embed fill:#eef6ff,stroke:#6699cc",
            "  classDef external stroke-dasharray: 3 3,color:#888888",
        ]
        edges, externals = [], {}

        def walk(node, depth):
            pad = "  " * depth
            nid = self.node_id(node)
            if node.kind == "step":
                text = node.name
                if node.chain_cmds:
                    text += "<br/>" + " · ".join(node.chain_cmds)
                lines.append(f'{pad}{nid}["{self.label(text)}"]')
                return
            title = node.name
            if node.kind == "embed":
                title += f" [flow: {node.workflow}]"
            if node.replan:
                title += " (at replan)"
            lines.append(f'{pad}subgraph {nid}["{self.label(title)}"]')
            for c in node.children:
                walk(c, depth + 1)
            lines.append(f"{pad}end")
            if node.kind == "embed":
                lines.append(f"{pad}class {nid} embed")
            if node.replan:
                lines.append(f"{pad}class {nid} replan")

        for child in root.children:
            walk(child, 1)

        for node in root.subtree():
            for inp in node.inputs:
                src = self.resolve_input(node, inp)
                if src is not None:
                    edges.append(f"  {self.node_id(src)} --> {self.node_id(node)}")
                else:
                    ext = externals.setdefault(
                        inp, f"ext__{re.sub(r'[^A-Za-z0-9_]', '_', inp)}"
                    )
                    edges.append(f"  {ext} -.-> {self.node_id(node)}")

        for inp, ext in sorted(externals.items()):
            lines.append(f'  {ext}(["{self.label(inp)} (external)"]):::external')
        lines.extend(edges)
        return "\n".join(lines) + "\n"

    # ---------- flows.json emission ----------

    def emit_flow_graph(self, root):
        """One flow as a graph: the same expanded tree and input resolution the
        mermaid emitter walks, as data. Nodes come in preorder so a node's
        `parent` always appears earlier (the React Flow sub-flow contract)."""
        nodes = []
        for node in root.subtree():
            if node is root:
                continue
            entry = {
                "id": self.node_id(node),
                "parent": None if node.parent is root else self.node_id(node.parent),
                "kind": node.kind,
                "name": node.name,
                "mission": node.mission,
                "replan": node.replan,
            }
            if node.kind == "step":
                entry["task"] = node.name
                entry["chain"] = list(node.chain_cmds)
                entry["inputs"] = list(node.inputs)
            elif node.kind == "embed":
                entry["workflow"] = node.workflow
            nodes.append(entry)

        edges, externals = [], {}
        for node in root.subtree():
            for inp in node.inputs:
                src = self.resolve_input(node, inp)
                if src is not None:
                    source = self.node_id(src)
                    external = False
                else:
                    source = externals.setdefault(
                        inp, f"ext__{re.sub(r'[^A-Za-z0-9_]', '_', inp)}"
                    )
                    external = True
                edges.append({
                    "source": source,
                    "target": self.node_id(node),
                    "input": inp,
                    "external": external,
                })
        # inputs satisfied outside this flow: synthetic nodes, like the
        # mermaid emitter's dashed "(external)" stadiums
        for inp, ext in sorted(externals.items()):
            entry = {
                "id": ext,
                "parent": None,
                "kind": "external",
                "name": inp,
                "mission": "",
                "replan": False,
            }
            if inp in self.tasks:
                entry["task"] = inp
            nodes.append(entry)
        return {"mission": root.mission, "nodes": nodes, "edges": edges}

    def emit_flows_doc(self, expanded, schemas):
        """The whole flows.json document. Task schemas are embedded once,
        keyed by task name (nodes reference them via their `task` field), so
        a renderer needs no further fetches; `output` is the raw mini-DSL
        expression for compact key/type display."""
        return {
            "format_version": FLOWS_FORMAT_VERSION,
            "schema_version": SCHEMA_VERSION,
            "$comment": GENERATED_NOTE,
            "tasks": {
                task: {"output": self.tasks[task], "schema": schemas[task]}
                for task in sorted(self.tasks)
            },
            "flows": {
                name: self.emit_flow_graph(root) for name, root in expanded.items()
            },
        }

    # ---------- driver ----------

    def run(self, skill_dir=None, script_check=True):
        self.check_document()
        expanded = self.check_flows()

        # unreachable-type warning: everything should hang off some task
        if self.tasks:
            seeds = {
                t
                for output in self.tasks.values()
                for expr in output.values()
                for t in self.type_refs(expr)
            }
            reachable = self.type_closure(seeds)
            for name in self.types:
                if name not in reachable:
                    self.warn(f"types.{name}", "not reachable from any task output")

        if script_check and skill_dir is not None and not self.errors:
            self.check_scripts(skill_dir)

        schemas = {}
        diagrams = {}
        flows_doc = {}
        if not self.errors:
            schemas = {task: self.compile_task_schema(task) for task in self.tasks}
            diagrams = {
                name: self.emit_mermaid(name, root) for name, root in expanded.items()
            }
            flows_doc = self.emit_flows_doc(expanded, schemas)
        return schemas, diagrams, flows_doc


def main(argv=None):
    repo = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--skill-dir",
        type=Path,
        default=repo / "skills" / "research-step",
        help="the research-step skill directory (default: skills/research-step)",
    )
    ap.add_argument(
        "--no-script-check",
        action="store_true",
        help="skip the task-output-keys.sh compatibility check",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="validate only; do not write assets/compiled/",
    )
    args = ap.parse_args(argv)

    try:
        import yaml
    except ImportError:
        print(
            "compile-schemas: python3 cannot import yaml (PyYAML) — pip install pyyaml",
            file=sys.stderr,
        )
        return 1

    schemas_path = args.skill_dir / "assets" / "schemas.yaml"
    try:
        with open(schemas_path) as f:
            doc = yaml.safe_load(f)
    except Exception as e:
        print(f"compile-schemas: cannot read {schemas_path}: {e}", file=sys.stderr)
        return 1

    compiler = Compiler(doc)
    schemas, diagrams, flows_doc = compiler.run(
        skill_dir=args.skill_dir, script_check=not args.no_script_check
    )

    for w in compiler.warnings:
        print(f"compile-schemas: warning: {w}", file=sys.stderr)
    if compiler.errors:
        for e in compiler.errors:
            print(f"compile-schemas: error: {e}", file=sys.stderr)
        print(f"compile-schemas: {len(compiler.errors)} error(s)", file=sys.stderr)
        return 1

    if not args.check:
        out_dir = args.skill_dir / "assets" / "compiled"
        out_dir.mkdir(parents=True, exist_ok=True)
        for stale in (
            list(out_dir.glob("*.schema.json"))
            + list(out_dir.glob("*.mmd"))
            + list(out_dir.glob("flows.json"))
        ):
            stale.unlink()
        for task, schema in schemas.items():
            (out_dir / f"{task}.schema.json").write_text(
                json.dumps(schema, indent=2, sort_keys=True) + "\n"
            )
        for flow, mmd in diagrams.items():
            (out_dir / f"{flow}.mmd").write_text(mmd)
        (out_dir / "flows.json").write_text(
            json.dumps(flows_doc, indent=2, sort_keys=True) + "\n"
        )

    print(
        f"compile-schemas: ok — {len(compiler.types)} types, "
        f"{len(schemas)} task schemas, {len(diagrams)} flow diagrams, flows.json"
        + ("" if args.check else f" -> {args.skill_dir / 'assets' / 'compiled'}")
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
