#!/usr/bin/env python3
"""Create uncommitted Quarto viewer pages for discovered LaTeX papers."""

import hashlib
import html
import json
import os
import posixpath
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import quote

GENERATED_MARKER = (
    "<!-- Generated by asta-plugins. Commit a custom viewer to override it. -->"
)
HASH_MARKER = re.compile(r"^<!-- Generated by asta-plugins sha256=([a-f0-9]{64}) -->$")


def tracked_files() -> set[str] | None:
    try:
        result = subprocess.run(
            ["git", "ls-files", "--cached", "-z"],
            capture_output=True,
            check=False,
            env={**os.environ, "LC_ALL": "C"},
        )
    except OSError:
        print(
            "paper-viewer: Git unavailable; preserving existing pages", file=sys.stderr
        )
        return None
    if result.returncode == 0:
        return {os.fsdecode(path) for path in result.stdout.split(b"\0") if path}
    if result.returncode == 128 and b"not a git repository" in result.stderr.lower():
        return set()
    print(
        "paper-viewer: Git ownership unknown; preserving existing pages",
        file=sys.stderr,
    )
    return None


def managed_viewer(path: Path, tracked: set[str] | None) -> bool:
    # A committed copy is user-owned even if it retains the generated marker.
    if tracked is None or path.as_posix() in tracked or path.is_symlink():
        return False
    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return False
    lines = content.splitlines(keepends=True)
    for index, line in enumerate(lines):
        match = HASH_MARKER.fullmatch(line.rstrip("\r\n"))
        if match:
            body = "".join(lines[:index] + lines[index + 1 :])
            if hashlib.sha256(body.encode()).hexdigest() == match[1]:
                return True
        elif line.rstrip("\r\n") != GENERATED_MARKER:
            continue
        print(
            f"paper-viewer: preserving edited or legacy viewer {path}", file=sys.stderr
        )
        return False
    return False


def remove_orphan_viewers(directories: list[str], tracked: set[str] | None) -> None:
    for root, children, files in os.walk(".", followlinks=False):
        folder = Path(root)
        children[:] = [
            name
            for name in children
            if not name.startswith(".")
            and name
            not in {
                "_site",
                "_extensions",
                "build",
                "node_modules",
                "venv",
                "paper-previews",
            }
            and not (folder / name).is_symlink()
            and not (folder / name / ".git").exists()
        ]
        if folder.name != "html" or "index.qmd" not in files:
            continue
        path = folder / "index.qmd"
        if folder.parent.as_posix() not in directories and managed_viewer(
            path, tracked
        ):
            path.unlink()


def paper_directories(data: object) -> list[str]:
    if not isinstance(data, dict) or not isinstance(data.get("papers"), list):
        raise ValueError(
            "Expected discovery JSON with a 'papers' array of relative directory names"
        )
    for directory in data["papers"]:
        if (
            not isinstance(directory, str)
            or any(
                part in {"", ".", ".."} or part.startswith("-")
                for part in directory.split("/")
            )
            or any(ord(char) < 32 or ord(char) == 127 for char in directory)
        ):
            raise ValueError(f"Invalid paper directory: {directory!r}")
    return data["papers"]


def create_viewer(
    directory: str, tracked: set[str] | None, main_file: str = ""
) -> None:
    folder = Path(directory) / "html"
    # Nested repositories and symlinks belong to their own project.
    if any(
        path.is_symlink() or (path != Path(".") and (path / ".git").exists())
        for path in [*folder.parents, folder]
    ):
        return
    if any(
        (folder / f"index.{suffix}").exists()
        or (folder / f"index.{suffix}").is_symlink()
        for suffix in ("md", "html")
    ):
        return
    page = folder / "index.qmd"
    if page.is_symlink() or (page.exists() and not managed_viewer(page, tracked)):
        return
    folder.mkdir(parents=True, exist_ok=True)
    title = "Paper HTML" if directory == "paper" else f"{directory} HTML"
    target = posixpath.relpath(f"paper-previews/{directory}", folder.as_posix())
    target = quote(target, safe="/.")
    source = f"{directory}/{main_file}"
    content = f"""---
title: {json.dumps(title)}
---

{GENERATED_MARKER}

```{{=html}}
<p>The paper is written in <code>{html.escape(source)}</code>.
The preview builds PDF and HTML from that LaTeX source.</p>
<div data-paper-preview="{html.escape(target, quote=True)}">
<p data-paper-links></p>
<div data-paper-html>
<p>The paper artifacts appear after the preview build. If HTML conversion fails,
use the PDF link when available.</p>
</div>
</div>

<script>
(() => {{
  const host = document.querySelector('[data-paper-preview]');
  const links = host.querySelector('[data-paper-links]');
  const htmlHost = host.querySelector('[data-paper-html]');
  const base = host.dataset.paperPreview;
  function addLink(url, label) {{
    const link = document.createElement('a');
    link.href = url;
    link.textContent = label;
    if (links.childNodes.length) links.append(' · ');
    links.append(link);
  }}
  fetch(base + '/main.pdf', {{ method: 'HEAD' }}).then(response => {{
    if (response.ok) addLink(base + '/main.pdf', 'Open paper PDF');
  }}).catch(() => {{}});
  const url = base + '/html/index.html';
  fetch(url, {{ method: 'HEAD' }}).then(response => {{
    if (!response.ok) return;
    addLink(url, 'Open full HTML paper');
    const frame = document.createElement('iframe');
    frame.src = url;
    frame.title = {json.dumps(title).replace("<", chr(92) + "u003c")};
    frame.setAttribute('sandbox', 'allow-same-origin allow-popups allow-popups-to-escape-sandbox');
    frame.style.cssText = 'width:100%;min-height:70vh;border:0';
    frame.addEventListener('load', () => {{
      if (!frame.contentDocument) return;
      for (const link of frame.contentDocument.querySelectorAll('a[href]')) {{
        let destination;
        try {{ destination = new URL(link.getAttribute('href'), new URL(url, document.baseURI)); }}
        catch {{ continue; }}
        if (['http:', 'https:'].includes(destination.protocol) && destination.origin !== location.origin) {{
          link.target = '_blank';
          link.rel = 'noopener noreferrer';
        }}
      }}
    }});
    htmlHost.replaceChildren(frame);
  }}).catch(() => {{}});
}})();
</script>
```
"""
    body = content.replace(GENERATED_MARKER + "\n", "", 1)
    marker = (
        "<!-- Generated by asta-plugins sha256="
        + hashlib.sha256(body.encode()).hexdigest()
        + " -->"
    )
    page.write_text(content.replace(GENERATED_MARKER, marker, 1), encoding="utf-8")


def main() -> None:
    try:
        data = json.load(sys.stdin)
        directories = paper_directories(data)
        main_files = data.get("main_files", {})
        if not isinstance(main_files, dict) or any(
            not isinstance(name, str) for name in main_files.values()
        ):
            raise ValueError("Expected 'main_files' to map directories to source names")
    except ValueError as error:
        print(f"paper-viewer: {error}", file=sys.stderr)
        raise SystemExit(1) from None
    tracked = tracked_files()
    remove_orphan_viewers(directories, tracked)
    for directory in directories:
        create_viewer(directory, tracked, main_files.get(directory, "main.tex"))


if __name__ == "__main__":
    main()
