#!/usr/bin/env python3
"""Create uncommitted Quarto viewer pages for discovered LaTeX papers."""

import html
import json
import posixpath
import sys
from pathlib import Path
from urllib.parse import quote


def paper_directories(data: object) -> list[str]:
    if not isinstance(data, dict) or not isinstance(data.get("papers"), list):
        raise ValueError(
            "Expected discovery JSON with a 'papers' array of relative directory names"
        )
    for directory in data["papers"]:
        if (
            not isinstance(directory, str)
            or any(
                part in {"", ".", ".."} or part.startswith("-")
                for part in directory.split("/")
            )
            or any(ord(char) < 32 or ord(char) == 127 for char in directory)
        ):
            raise ValueError(f"Invalid paper directory: {directory!r}")
    return data["papers"]


def create_viewer(directory: str) -> None:
    folder = Path(directory) / "html"
    # Any local viewer is an explicit customization, including a symlink.
    if any(path.is_symlink() for path in [Path(directory), *folder.parents, folder]):
        return
    if any(
        (folder / f"index.{suffix}").exists()
        or (folder / f"index.{suffix}").is_symlink()
        for suffix in ("qmd", "md", "html")
    ):
        return
    folder.mkdir(parents=True, exist_ok=True)
    title = "Paper HTML" if directory == "paper" else f"{directory} HTML"
    target = posixpath.relpath(f"paper-previews/{directory}", folder.as_posix())
    target = quote(target, safe="/.")
    (folder / "index.qmd").write_text(
        f"""---
title: {json.dumps(title)}
---

<!-- Generated by asta-plugins. Commit a custom viewer to override it. -->

```{{=html}}
<p>The paper is written in <code>{html.escape(directory)}/main.tex</code>.
The preview builds PDF and HTML from that LaTeX source.</p>
<div data-paper-preview="{html.escape(target, quote=True)}">
<p data-paper-links></p>
<div data-paper-html>
<p>The paper artifacts appear after the preview build. If HTML conversion fails,
use the PDF link when available.</p>
</div>
</div>

<script>
(() => {{
  const host = document.querySelector('[data-paper-preview]');
  const links = host.querySelector('[data-paper-links]');
  const htmlHost = host.querySelector('[data-paper-html]');
  const base = host.dataset.paperPreview;
  function addLink(url, label) {{
    const link = document.createElement('a');
    link.href = url;
    link.textContent = label;
    if (links.childNodes.length) links.append(' · ');
    links.append(link);
  }}
  fetch(base + '/main.pdf', {{ method: 'HEAD' }}).then(response => {{
    if (response.ok) addLink(base + '/main.pdf', 'Open paper PDF');
  }}).catch(() => {{}});
  const url = base + '/html/index.html';
  fetch(url, {{ method: 'HEAD' }}).then(response => {{
    if (!response.ok) return;
    addLink(url, 'Open full HTML paper');
    const frame = document.createElement('iframe');
    frame.src = url;
    frame.title = {json.dumps(title).replace("<", chr(92) + "u003c")};
    frame.setAttribute('sandbox', 'allow-same-origin allow-popups allow-popups-to-escape-sandbox');
    frame.style.cssText = 'width:100%;min-height:70vh;border:0';
    frame.addEventListener('load', () => {{
      if (!frame.contentDocument) return;
      for (const link of frame.contentDocument.querySelectorAll('a[href]')) {{
        let destination;
        try {{ destination = new URL(link.getAttribute('href'), new URL(url, document.baseURI)); }}
        catch {{ continue; }}
        if (['http:', 'https:'].includes(destination.protocol) && destination.origin !== location.origin) {{
          link.target = '_blank';
          link.rel = 'noopener noreferrer';
        }}
      }}
    }});
    htmlHost.replaceChildren(frame);
  }}).catch(() => {{}});
}})();
</script>
```
""",
        encoding="utf-8",
    )


def main() -> None:
    try:
        directories = paper_directories(json.load(sys.stdin))
    except ValueError as error:
        print(f"paper-viewer: {error}", file=sys.stderr)
        raise SystemExit(1) from None
    for directory in directories:
        create_viewer(directory)


if __name__ == "__main__":
    main()
