#!/usr/bin/env python3
"""Create uncommitted Quarto viewer pages for discovered LaTeX papers."""

import html
import json
import posixpath
import sys
from pathlib import Path
from urllib.parse import quote


def create_viewer(directory: str) -> None:
    parts = Path(directory).parts
    if (
        not parts
        or Path(directory).is_absolute()
        or any(part in {".", ".."} or part.startswith("-") for part in parts)
        or any(ord(char) < 32 or ord(char) == 127 for char in directory)
    ):
        raise ValueError(f"Invalid paper directory: {directory!r}")
    folder = Path(directory) / "html"
    # Any local viewer is an explicit customization, including a symlink.
    if any(path.is_symlink() for path in [Path(directory), *folder.parents, folder]):
        return
    if any(
        (folder / f"index.{suffix}").exists()
        or (folder / f"index.{suffix}").is_symlink()
        for suffix in ("qmd", "md", "html")
    ):
        return
    folder.mkdir(parents=True, exist_ok=True)
    title = "Paper HTML" if directory == "paper" else f"{directory} HTML"
    target = posixpath.relpath(f"paper-previews/{directory}", folder.as_posix())
    target = quote(target, safe="/.")
    (folder / "index.qmd").write_text(
        f"""---
title: {json.dumps(title)}
---

<!-- Generated by asta-plugins. Commit a custom viewer to override it. -->

The paper is written in <code>{html.escape(directory)}/main.tex</code>.
The preview builds PDF and HTML from that LaTeX source.

[Open paper PDF]({target}/main.pdf) · [Open full HTML paper]({target}/html/index.html)

<div data-paper-preview="{html.escape(target, quote=True)}">
<p>The HTML rendition appears after the preview build. If conversion fails,
use the PDF above.</p>
</div>

```{{=html}}
<script>
(() => {{
  const host = document.querySelector('[data-paper-preview]');
  const url = host.dataset.paperPreview + '/html/index.html';
  fetch(url, {{ method: 'HEAD' }}).then(response => {{
    if (!response.ok) return;
    const frame = document.createElement('iframe');
    frame.src = url;
    frame.title = {json.dumps(title).replace("<", chr(92) + "u003c")};
    frame.setAttribute('sandbox', 'allow-same-origin');
    frame.style.cssText = 'width:100%;min-height:70vh;border:0';
    host.replaceChildren(frame);
  }}).catch(() => {{}});
}})();
</script>
```
""",
        encoding="utf-8",
    )


def main() -> None:
    for directory in json.load(sys.stdin)["papers"]:
        create_viewer(directory)


if __name__ == "__main__":
    main()
